# Generated by Django 4.2.6 on 2023-10-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_task_current_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='current_time',
        ),
        migrations.AddField(
            model_name='task',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
